name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Run Playwright tests
      run: npx playwright test
      
    - name: Generate Allure Report
      if: always()
      run: npx allure generate allure-results -o allure-report --clean

    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v4

    - name: Upload Pages artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report

    - name: Deploy to GitHub Pages
      if: always()
      uses: actions/deploy-pages@v4
      with:
        path: allure-report